# coding: utf-8

"""
    MeMaS APIs

    This is the Control Plane and Data Plane APIs for MeMaS (Memory Management Service). See https://github.com/memas-ai/MeMaS for more details.  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Contact: max.yu@memas.ai
    Generated by: https://openapi-generator.tech
"""

import unittest

import memas_sdk
from memas_sdk.model.citation import Citation
from memas_sdk import configuration


class TestCitation(unittest.TestCase):
    """Citation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
