# coding: utf-8

"""
    MeMaS CP APIs

    This is the Control Plane client for MeMaS (Memory Management Service).  See https://github.com/memas-ai/MeMaS for more details.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: max.yu@memas.ai
    Generated by: https://openapi-generator.tech
"""

import unittest

import memas_sdk
from memas_sdk.model.namespace_exist_error import NamespaceExistError
from memas_sdk import configuration


class TestNamespaceExistError(unittest.TestCase):
    """NamespaceExistError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
